// Example application demonstrating the Buck2 configuration system.
//
// Two ways to consume configuration values are shown here:
//
//   1. Constants  — imported from the `app_config` crate.
//      Strongly typed (bool, i64, &str) and always consistent with the
//      --target-platforms used at build time.
//
//   2. --cfg flags — resolved from constraints by the toolchain.
//      Enables conditional compilation without an explicit dependency.

// ── Constants from the generated config library ───────────────────────────

// `app_config` is the rust_library compiled from config.rs which was
// generated by config_codegen().  It exposes every schema field as a
// `pub const` in the crate root.
extern crate app_config;

fn print_constants() {
    println!("=== Configuration constants ===");
    println!("  ARCH       = {}", app_config::ARCH);
    println!("  BUILD_MODE = {}", app_config::BUILD_MODE);
    println!("  HEAP_SIZE  = {} bytes", app_config::HEAP_SIZE);
    println!("  HAS_QEMU   = {}", app_config::HAS_QEMU);
    println!("  HAS_UART   = {}", app_config::HAS_UART);
}

// ── Conditional compilation via --cfg flags ───────────────────────────────
//
// The toolchain (toolchains/BUCK) passes --cfg=arch="riscv64" etc. for every
// crate compiled in a given configuration.  No extra dependency is needed.

fn platform_description() -> &'static str {
    #[cfg(arch = "riscv64")]
    {
        "RISC-V 64-bit"
    }
    #[cfg(arch = "aarch64")]
    {
        "AArch64"
    }
    #[cfg(arch = "x86_64")]
    {
        "x86-64"
    }
    #[cfg(not(any(arch = "riscv64", arch = "aarch64", arch = "x86_64")))]
    {
        "unknown"
    }
}

#[cfg(has_qemu)]
fn qemu_note() {
    println!("  [QEMU] virtio transport enabled");
}

#[cfg(not(has_qemu))]
fn qemu_note() {}

#[cfg(has_uart)]
fn uart_note() {
    println!("  [UART] serial driver enabled");
}

#[cfg(not(has_uart))]
fn uart_note() {}

#[cfg(build_mode = "release")]
fn mode_note() {
    println!("  Optimised release build");
}

#[cfg(build_mode = "debug")]
fn mode_note() {
    println!("  Debug build (assertions enabled)");
}

fn main() {
    print_constants();

    println!("\n=== Conditional compilation results ===");
    println!("  Platform: {}", platform_description());
    qemu_note();
    uart_note();
    mode_note();
}
